### ISSUE TITLE
Fix issue for mergetest pull request

### ISSUE THREAD

**Issue by jjwesse** [LegumeFederation/cmap-js#113]
`npm run test`  fails with error: 

```
'__moduleExports' is not exported by node_modules/rollup-plugin-node-resolve/src/empty.js (imported by commonjs-proxy:/workspaces/cmap-js/node_modules/object-inspect/util.inspect.js). For help fixing this error see https://github.com/rollup/rollup/wiki/Troubleshooting#name-is-not-exported-by-module
Error: '__moduleExports' is not exported by node_modules/rollup-plugin-node-resolve/src/empty.js (imported by commonjs-proxy:/workspaces/cmap-js/node_modules/object-inspect/util.inspect.js). For help fixing this error see https://github.com/rollup/rollup/wiki/Troubleshooting#name-is-not-exported-by-module
    at error (/workspaces/cmap-js/node_modules/rollup/src/utils/error.js:2:14)
    at Module.trace (/workspaces/cmap-js/node_modules/rollup/src/Module.js:375:4)
    at ModuleScope.findDeclaration (/workspaces/cmap-js/node_modules/rollup/src/ast/scopes/ModuleScope.js:52:22)
    at Node.bind (/workspaces/cmap-js/node_modules/rollup/src/ast/nodes/ExportDefaultDeclaration.js:30:37)
    at Module.bindReferences (/workspaces/cmap-js/node_modules/rollup/src/Module.js:274:9)
    at /workspaces/cmap-js/node_modules/rollup/src/Bundle.js:122:44
    at Array.forEach (<anonymous>)
    at /workspaces/cmap-js/node_modules/rollup/src/Bundle.js:122:18
```

**Comment by nathanweeks** [comment]
mergetest PR closed; feature branches were/are being merged separately
